[package]
name = "PhotonMock"
version = "1.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "mainnet" }

[addresses]
PhotonDevAddress = "760637102c573ea852d0da8865872d62f04c2d8f145e4545a18a28f634698eeb"
